### ISSUE TITLE
Question about `dense & merge` in ablation study

### ISSUE THREAD

**Issue by LeoXing1996** [ziqipang/RandAR#5]
Thanks for sharing this great work. 

In `Ablation Study: Design Choices of Position Instruction Tokens.`, you mention **"the Merge design shows degraded performance when using parallel decoding directly."** 
Since the number of input tokens and output tokens are same for AR models, how could you conduct parallel decoding without explicit position instruct?
Could you provide more detail (or pseudmo code) for the parallel decoding for `merge & dense` setting?

**Comment by ziqipang** [comment]
@LeoXing1996 Thanks for your interest! I am busy with ICCV right now. Could you please remind me again by @ me next week. I will give you a detailed explanation then.

**Comment by LeoXing1996** [comment]
Hey @ziqipang, are you still busy? Is there any update on this issue? 🙋‍

**Comment by ziqipang** [comment]
@LeoXing1996 Thanks for the patience!

Let's begin with how RandAR conducts parallel decoding. Suppose we have the latest token to be $x_k$, and we want to generate the tokens for positions with position instruction tokens of $p_{k+1}$ and $p_{k+2}$. We will concatenate the generated sequence $[..., p_{k}, x_{k}]$ with the new position instruction token into $[..., p_{k}, x_{k}, p_{k+1}, p_{k+2}]$ and decode the tokens for $p_{k+1}$ and $p_{k+2}$. This process is demonstrated in the paper.

After understanding how RandAR conducts parallel decoding, let's take a look at **what needs modifications for the dense+merge case**. This time, a position instruction token cannot exist without an image token, so we have to change $p_{k+1}$ to $p_{k+1} + x_{k}$ and $p_{k+2}$ to $p_{k+2} + x_{k}$. Given the previous sequences of [..., (p_{k} + x_{k-1})], we concat the new tokens to be decoded to this sequence and have [..., (p_{k} + x_{k-1}), (p_{k+1} + x_{k}), (p_{k+2} + x_{k})]. The tokens are decoded from the last two positions. I hope this approach makes sense to you!

Please let me know if you have additional questions!

**Comment by LeoXing1996** [comment]
**@ziqipang** Thanks for your detailed reply! If I understand correctly, the training and inference processes can be illustrated as follows:

```
Training:
    Loss:  |<------------ NCE -------------->|
    Out:   <IMG_1>      <IMG_2>        <IMG_3>   ...    <IGNORE>
    Inp: <CLS + P_1> <IMG_1 + P_2> <IMG_2 + P_3> ... <IMG_N + P_N>

Inference:
* Round 1: <P_1>
    Out:   <IMG_1>
    Inp: <CLS + P_1>

* Round 2: <P_2>
    Out:   <IMG_1>      <IMG_2>
    Inp: <CLS + P_1> <IMG_1 + P_2>

* Round 3: <P_3> & <P_4>
    Out:   <IMG_1>      <IMG_2>       <IMG_3>      <IMG_4>
    Inp: <CLS + P_1> <IMG_1 + P_2> <IMG_2 + P_3> <IMG_2 + P_4>
```

There seems to be a discrepancy between training and inference, which leads to a performance drop during inference.  

Is my understanding correct?
